apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: raj-mysql-rs
  labels:
    app: mysql
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-dbcontainer
        image: 292055316436.dkr.ecr.us-east-1.amazonaws.com/raj:db_v0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
