apiVersion: v1
kind: Pod
metadata:
  name: raj-mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-dbcontainer
    image: 292055316436.dkr.ecr.us-east-1.amazonaws.com/raj:db_v0.1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
